import { Box, Heading, Text } from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box h="100vh" bg="app.bg" color="">
          <Heading fontSize={"30px"} fontWeight={600}>
            Dispatch Orders
          </Heading>
          <Text
            // fontFamily={"GT Walsheim Pro"}
            fontSize={"30px"}
            fontWeight={600}
          >
            Finesse Pharmacy
          </Text>
        </Box>
      </main>
    </div>
  );
}
